version: '3'
services:
  node-app-cake-shop:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
    # env_file:
    #   - ./.env
    command: npm run dev
  postgres-cakeshop:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=abcduser
      - POSTGRES_PASSWORD=abcdpsw
    volumes:
      - D:\miniproject\backend\5_6267292960669304431